-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 22:53:36 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amun12
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amun12
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amun12` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `amun12` ;

-- -----------------------------------------------------
-- Table `amun12`.`lista_paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`lista_paises` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(80) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(200) NOT NULL COMMENT '',
  `nome_cracha` VARCHAR(45) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `cep` VARCHAR(20) NOT NULL COMMENT '',
  `cidade` VARCHAR(45) NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `bairro` VARCHAR(45) NOT NULL COMMENT '',
  `identification` VARCHAR(20) NOT NULL COMMENT '',
  `tipo` INT NOT NULL COMMENT '',
  `status` INT NOT NULL COMMENT '',
  `situacao_pagamento` INT NULL COMMENT '',
  `lista_paises_id` INT NOT NULL COMMENT '',
  `numero` VARCHAR(45) NULL COMMENT '',
  `foto` VARCHAR(500) NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '',
  INDEX `fk_usuario_lista_paises1_idx` (`lista_paises_id` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_lista_paises1`
    FOREIGN KEY (`lista_paises_id`)
    REFERENCES `amun12`.`lista_paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`delegacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`delegacao` (
  `iddelegacao` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `universidade` VARCHAR(200) NOT NULL COMMENT '',
  `professor` INT NOT NULL COMMENT '',
  `curso` VARCHAR(45) NOT NULL COMMENT '',
  `qtd_integrantes` INT NOT NULL COMMENT '',
  `delegacao_idusuario` INT NOT NULL COMMENT '',
  `qtd_gratuidade` INT NOT NULL COMMENT '',
  `qtd_pacotes` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`iddelegacao`)  COMMENT '',
  INDEX `fk_delegacao_usuario1_idx` (`delegacao_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_delegacao_usuario1`
    FOREIGN KEY (`delegacao_idusuario`)
    REFERENCES `amun12`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`paises` (
  `idpaises` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `qtd_participantes` INT NOT NULL COMMENT '',
  `delegacao_iddelegacao` INT NULL COMMENT '',
  PRIMARY KEY (`idpaises`)  COMMENT '',
  INDEX `fk_paises_delegacao1_idx` (`delegacao_iddelegacao` ASC)  COMMENT '',
  CONSTRAINT `fk_paises_delegacao1`
    FOREIGN KEY (`delegacao_iddelegacao`)
    REFERENCES `amun12`.`delegacao` (`iddelegacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`Comite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`Comite` (
  `idComite` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idComite`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`usuario_has_delegacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`usuario_has_delegacao` (
  `usuario_idusuario` INT NOT NULL COMMENT '',
  `comite_iddelegacao` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario_idusuario`, `comite_iddelegacao`)  COMMENT '',
  INDEX `fk_usuario_has_comite_comite1_idx` (`comite_iddelegacao` ASC)  COMMENT '',
  INDEX `fk_usuario_has_comite_usuario_idx` (`usuario_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_has_comite_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `amun12`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_comite_comite1`
    FOREIGN KEY (`comite_iddelegacao`)
    REFERENCES `amun12`.`delegacao` (`iddelegacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`paises_opcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`paises_opcoes` (
  `id_paises_opcoes` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `delegacao_iddelegacao` INT NOT NULL COMMENT '',
  `status_aprovacao` INT NOT NULL COMMENT '',
  `combinacao` VARCHAR(200) NOT NULL COMMENT '',
  INDEX `fk_paises_has_delegacao_delegacao1_idx` (`delegacao_iddelegacao` ASC)  COMMENT '',
  PRIMARY KEY (`id_paises_opcoes`)  COMMENT '',
  CONSTRAINT `fk_paises_has_delegacao_delegacao1`
    FOREIGN KEY (`delegacao_iddelegacao`)
    REFERENCES `amun12`.`delegacao` (`iddelegacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`Comite_has_paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`Comite_has_paises` (
  `qtd_vagas` INT NOT NULL COMMENT '',
  `paises_idpaises` INT NOT NULL COMMENT '',
  `Comite_idComite` INT NOT NULL COMMENT '',
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  INDEX `fk_Comite_has_paises_paises1_idx` (`paises_idpaises` ASC)  COMMENT '',
  INDEX `fk_Comite_has_paises_Comite1_idx` (`Comite_idComite` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_Comite_has_paises_paises1`
    FOREIGN KEY (`paises_idpaises`)
    REFERENCES `amun12`.`paises` (`idpaises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comite_has_paises_Comite1`
    FOREIGN KEY (`Comite_idComite`)
    REFERENCES `amun12`.`Comite` (`idComite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`delegado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`delegado` (
  `iddelegado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `nome_cracha` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(200) NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `identification` VARCHAR(45) NOT NULL COMMENT '',
  `delegacao_iddelegacao` INT NOT NULL COMMENT '',
  `Comite_has_paises_id` INT NULL COMMENT '',
  `facebook` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`iddelegado`)  COMMENT '',
  INDEX `fk_delegado_delegacao1_idx` (`delegacao_iddelegacao` ASC)  COMMENT '',
  INDEX `fk_delegado_Comite_has_paises1_idx` (`Comite_has_paises_id` ASC)  COMMENT '',
  CONSTRAINT `fk_delegado_delegacao1`
    FOREIGN KEY (`delegacao_iddelegacao`)
    REFERENCES `amun12`.`delegacao` (`iddelegacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delegado_Comite_has_paises1`
    FOREIGN KEY (`Comite_has_paises_id`)
    REFERENCES `amun12`.`Comite_has_paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`individual_pa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`individual_pa` (
  `idindividual_pa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `universidade` VARCHAR(100) NOT NULL COMMENT '',
  `curso` VARCHAR(100) NOT NULL COMMENT '',
  `professor` INT NOT NULL COMMENT '',
  `experiencia` VARCHAR(45) NOT NULL COMMENT '',
  `pergunta` VARCHAR(5126) NOT NULL COMMENT '',
  `delegation_interest` INT NOT NULL COMMENT '',
  `social_events` INT NOT NULL COMMENT '',
  `pa_idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idindividual_pa`)  COMMENT '',
  INDEX `fk_individual_pa_usuario1_idx` (`pa_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_individual_pa_usuario1`
    FOREIGN KEY (`pa_idusuario`)
    REFERENCES `amun12`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`individual_icty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`individual_icty` (
  `idindividual_icty` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `universidade` VARCHAR(100) NOT NULL COMMENT '',
  `curso` VARCHAR(100) NOT NULL COMMENT '',
  `professor` INT NOT NULL COMMENT '',
  `preferencies` VARCHAR(200) NOT NULL COMMENT '',
  `delegation_interest` INT NOT NULL COMMENT '',
  `social_events` INT NOT NULL COMMENT '',
  `icty_idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idindividual_icty`)  COMMENT '',
  INDEX `fk_individual_icty_usuario1_idx` (`icty_idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_individual_icty_usuario1`
    FOREIGN KEY (`icty_idusuario`)
    REFERENCES `amun12`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amun12`.`qtd_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amun12`.`qtd_vagas` (
  `id` INT NOT NULL COMMENT '',
  `qtd_vagas_delegacao` INT NOT NULL COMMENT '',
  `qtd_vagas_icty` INT NOT NULL COMMENT '',
  `qtd_vagas_pa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
