
INSERT INTO lista_paises(id,nome) VALUES (1,  'United States');
INSERT INTO lista_paises(id,nome) VALUES (2,  'Canada');
INSERT INTO lista_paises(id,nome) VALUES (3,  'Afghanistan');
INSERT INTO lista_paises(id,nome) VALUES (4,  'Albania');
INSERT INTO lista_paises(id,nome) VALUES (5,  'Algeria');
INSERT INTO lista_paises(id,nome) VALUES (6,  'American Samoa');
INSERT INTO lista_paises(id,nome) VALUES (7,  'Andorra');
INSERT INTO lista_paises(id,nome) VALUES (8,  'Angola');
INSERT INTO lista_paises(id,nome) VALUES (9,  'Anguilla');
INSERT INTO lista_paises(id,nome) VALUES (10,  'Antarctica');
INSERT INTO lista_paises(id,nome) VALUES (11,  'Antigua and/or Barbuda');
INSERT INTO lista_paises(id,nome) VALUES (12,  'Argentina');
INSERT INTO lista_paises(id,nome) VALUES (13,  'Armenia');
INSERT INTO lista_paises(id,nome) VALUES (14,  'Aruba');
INSERT INTO lista_paises(id,nome) VALUES (15,  'Australia');
INSERT INTO lista_paises(id,nome) VALUES (16,  'Austria');
INSERT INTO lista_paises(id,nome) VALUES (17,  'Azerbaijan');
INSERT INTO lista_paises(id,nome) VALUES (18,  'Bahamas');
INSERT INTO lista_paises(id,nome) VALUES (19,  'Bahrain');
INSERT INTO lista_paises(id,nome) VALUES (20,  'Bangladesh');
INSERT INTO lista_paises(id,nome) VALUES (21,  'Barbados');
INSERT INTO lista_paises(id,nome) VALUES (22,  'Belarus');
INSERT INTO lista_paises(id,nome) VALUES (23,  'Belgium');
INSERT INTO lista_paises(id,nome) VALUES (24,  'Belize');
INSERT INTO lista_paises(id,nome) VALUES (25,  'Benin');
INSERT INTO lista_paises(id,nome) VALUES (26,  'Bermuda');
INSERT INTO lista_paises(id,nome) VALUES (27,  'Bhutan');
INSERT INTO lista_paises(id,nome) VALUES (28,  'Bolivia');
INSERT INTO lista_paises(id,nome) VALUES (29,  'Bosnia and Herzegovina');
INSERT INTO lista_paises(id,nome) VALUES (30,  'Botswana');
INSERT INTO lista_paises(id,nome) VALUES (31, 'Bouvet Island');
INSERT INTO lista_paises(id,nome) VALUES (32, 'Brazil');
INSERT INTO lista_paises(id,nome) VALUES (33, 'British lndian Ocean Territory');
INSERT INTO lista_paises(id,nome) VALUES (34, 'Brunei Darussalam');
INSERT INTO lista_paises(id,nome) VALUES (35, 'Bulgaria');
INSERT INTO lista_paises(id,nome) VALUES (36, 'Burkina Faso');
INSERT INTO lista_paises(id,nome) VALUES (37, 'Burundi');
INSERT INTO lista_paises(id,nome) VALUES (38, 'Cambodia');
INSERT INTO lista_paises(id,nome) VALUES (39, 'Cameroon');
INSERT INTO lista_paises(id,nome) VALUES (40, 'Cape Verde');
INSERT INTO lista_paises(id,nome) VALUES (41, 'Cayman Islands');
INSERT INTO lista_paises(id,nome) VALUES (42, 'Central African Republic');
INSERT INTO lista_paises(id,nome) VALUES (43, 'Chad');
INSERT INTO lista_paises(id,nome) VALUES (44, 'Chile');
INSERT INTO lista_paises(id,nome) VALUES (45, 'China');
INSERT INTO lista_paises(id,nome) VALUES (46,'Christmas Island');
INSERT INTO lista_paises(id,nome) VALUES (47,'Cocos (Keeling) Islands');
INSERT INTO lista_paises(id,nome) VALUES (48,'Colombia');
INSERT INTO lista_paises(id,nome) VALUES (49,'Comoros');
INSERT INTO lista_paises(id,nome) VALUES (50,'Congo');
INSERT INTO lista_paises(id,nome) VALUES (51,'Cook Islands');
INSERT INTO lista_paises(id,nome) VALUES (52,'Costa Rica');
INSERT INTO lista_paises(id,nome) VALUES (53,'Croatia (Hrvatska)');
INSERT INTO lista_paises(id,nome) VALUES (54,'Cuba');
INSERT INTO lista_paises(id,nome) VALUES (55,'Cyprus');
INSERT INTO lista_paises(id,nome) VALUES (56,'Czech Republic');
INSERT INTO lista_paises(id,nome) VALUES (57,'Denmark');
INSERT INTO lista_paises(id,nome) VALUES (58,'Djibouti');
INSERT INTO lista_paises(id,nome) VALUES (59,'Dominica');
INSERT INTO lista_paises(id,nome) VALUES (60,'Dominican Republic');
INSERT INTO lista_paises(id,nome) VALUES (61,'East Timor');
INSERT INTO lista_paises(id,nome) VALUES (62,'Ecuador');
INSERT INTO lista_paises(id,nome) VALUES (63,'Egypt');
INSERT INTO lista_paises(id,nome) VALUES (64,'El Salvador');
INSERT INTO lista_paises(id,nome) VALUES (65,'Equatorial Guinea');
INSERT INTO lista_paises(id,nome) VALUES (66,'Eritrea');
INSERT INTO lista_paises(id,nome) VALUES (67,'Estonia');
INSERT INTO lista_paises(id,nome) VALUES (68,'Ethiopia');
INSERT INTO lista_paises(id,nome) VALUES (69,'Falkland Islands (Malvinas)');
INSERT INTO lista_paises(id,nome) VALUES (70,'Faroe Islands');
INSERT INTO lista_paises(id,nome) VALUES (71,'Fiji');
INSERT INTO lista_paises(id,nome) VALUES (72,'Finland');
INSERT INTO lista_paises(id,nome) VALUES (73,'France');
INSERT INTO lista_paises(id,nome) VALUES (74,'France, Metropolitan');
INSERT INTO lista_paises(id,nome) VALUES (75,'French Guiana');
INSERT INTO lista_paises(id,nome) VALUES (76,'French Polynesia');
INSERT INTO lista_paises(id,nome) VALUES (77,'French Southern Territories');
INSERT INTO lista_paises(id,nome) VALUES (78,'Gabon');
INSERT INTO lista_paises(id,nome) VALUES (79,'Gambia');
INSERT INTO lista_paises(id,nome) VALUES (80,'Georgia');
INSERT INTO lista_paises(id,nome) VALUES (81,'Germany');
INSERT INTO lista_paises(id,nome) VALUES (82,'Ghana');
INSERT INTO lista_paises(id,nome) VALUES (83,'Gibraltar');
INSERT INTO lista_paises(id,nome) VALUES (84,'Greece');
INSERT INTO lista_paises(id,nome) VALUES (85,'Greenland');
INSERT INTO lista_paises(id,nome) VALUES (86,'Grenada');
INSERT INTO lista_paises(id,nome) VALUES (87,'Guadeloupe');
INSERT INTO lista_paises(id,nome) VALUES (88,'Guam');
INSERT INTO lista_paises(id,nome) VALUES (89,'Guatemala');
INSERT INTO lista_paises(id,nome) VALUES (90,'Guinea');
INSERT INTO lista_paises(id,nome) VALUES (91,'Guinea-Bissau');
INSERT INTO lista_paises(id,nome) VALUES (92,'Guyana');
INSERT INTO lista_paises(id,nome) VALUES (93,'Haiti');
INSERT INTO lista_paises(id,nome) VALUES (94,'Heard and Mc Donald Islands');
INSERT INTO lista_paises(id,nome) VALUES (95,'Honduras');
INSERT INTO lista_paises(id,nome) VALUES (96,'Hong Kong');
INSERT INTO lista_paises(id,nome) VALUES (97,'Hungary');
INSERT INTO lista_paises(id,nome) VALUES (98,'Iceland');
INSERT INTO lista_paises(id,nome) VALUES (99,'India');
INSERT INTO lista_paises(id,nome) VALUES (100,'Indonesia');
INSERT INTO lista_paises(id,nome) VALUES (101,'Iran (Islamic Republic of)');
INSERT INTO lista_paises(id,nome) VALUES (102,'Iraq');
INSERT INTO lista_paises(id,nome) VALUES (103,'Ireland');
INSERT INTO lista_paises(id,nome) VALUES (104,'Israel');
INSERT INTO lista_paises(id,nome) VALUES (105,'Italy');
INSERT INTO lista_paises(id,nome) VALUES (106,'Ivory Coast');
INSERT INTO lista_paises(id,nome) VALUES (107,'Jamaica');
INSERT INTO lista_paises(id,nome) VALUES (108,'Japan');
INSERT INTO lista_paises(id,nome) VALUES (109,'Jordan');
INSERT INTO lista_paises(id,nome) VALUES (110,'Kazakhstan');
INSERT INTO lista_paises(id,nome) VALUES (111,'Kenya');
INSERT INTO lista_paises(id,nome) VALUES (112,'Kiribati');
INSERT INTO lista_paises(id,nome) VALUES (113,'Korea, Democratic People''s Republic of');
INSERT INTO lista_paises(id,nome) VALUES (114,'Korea, Republic of');
INSERT INTO lista_paises(id,nome) VALUES (115,'Kosovo');

INSERT INTO lista_paises(id,nome) VALUES (116, 'Kuwait');
INSERT INTO lista_paises(id,nome) VALUES (117, 'Kyrgyzstan');
INSERT INTO lista_paises(id,nome) VALUES (118, 'Lao People''s Democratic Republic');
INSERT INTO lista_paises(id,nome) VALUES (119, 'Latvia');
INSERT INTO lista_paises(id,nome) VALUES (120, 'Lebanon');
INSERT INTO lista_paises(id,nome) VALUES (121, 'Lesotho');
INSERT INTO lista_paises(id,nome) VALUES (122, 'Liberia');
INSERT INTO lista_paises(id,nome) VALUES (123, 'Libyan Arab Jamahiriya');
INSERT INTO lista_paises(id,nome) VALUES (124, 'Liechtenstein');
INSERT INTO lista_paises(id,nome) VALUES (125, 'Lithuania');
INSERT INTO lista_paises(id,nome) VALUES (126, 'Luxembourg');
INSERT INTO lista_paises(id,nome) VALUES (127, 'Macau');
INSERT INTO lista_paises(id,nome) VALUES (128, 'Macedonia');
INSERT INTO lista_paises(id,nome) VALUES (129, 'Madagascar');
INSERT INTO lista_paises(id,nome) VALUES (130, 'Malawi');
INSERT INTO lista_paises(id,nome) VALUES (131, 'Malaysia');
INSERT INTO lista_paises(id,nome) VALUES (132, 'Maldives');
INSERT INTO lista_paises(id,nome) VALUES (133, 'Mali');
INSERT INTO lista_paises(id,nome) VALUES (134, 'Malta');
INSERT INTO lista_paises(id,nome) VALUES (135, 'Marshall Islands');
INSERT INTO lista_paises(id,nome) VALUES (136, 'Martinique');
INSERT INTO lista_paises(id,nome) VALUES (137, 'Mauritania');
INSERT INTO lista_paises(id,nome) VALUES (138, 'Mauritius');
INSERT INTO lista_paises(id,nome) VALUES (139, 'Mayotte');
INSERT INTO lista_paises(id,nome) VALUES (140, 'Mexico');
INSERT INTO lista_paises(id,nome) VALUES (141, 'Micronesia, Federated States of');
INSERT INTO lista_paises(id,nome) VALUES (142, 'Moldova, Republic of');
INSERT INTO lista_paises(id,nome) VALUES (143, 'Monaco');
INSERT INTO lista_paises(id,nome) VALUES (144, 'Mongolia');
INSERT INTO lista_paises(id,nome) VALUES (145, 'Montenegro');
INSERT INTO lista_paises(id,nome) VALUES (146, 'Montserrat');
INSERT INTO lista_paises(id,nome) VALUES (147, 'Morocco');
INSERT INTO lista_paises(id,nome) VALUES (148, 'Mozambique');
INSERT INTO lista_paises(id,nome) VALUES (149, 'Myanmar');
INSERT INTO lista_paises(id,nome) VALUES (150, 'Namibia');
INSERT INTO lista_paises(id,nome) VALUES (151, 'Nauru');
INSERT INTO lista_paises(id,nome) VALUES (152, 'Nepal');
INSERT INTO lista_paises(id,nome) VALUES (153, 'Netherlands');
INSERT INTO lista_paises(id,nome) VALUES (154, 'Netherlands Antilles');
INSERT INTO lista_paises(id,nome) VALUES (155, 'New Caledonia');
INSERT INTO lista_paises(id,nome) VALUES (156, 'New Zealand');
INSERT INTO lista_paises(id,nome) VALUES (157, 'Nicaragua');
INSERT INTO lista_paises(id,nome) VALUES (158, 'Niger');
INSERT INTO lista_paises(id,nome) VALUES (159, 'Nigeria');
INSERT INTO lista_paises(id,nome) VALUES (160, 'Niue');
INSERT INTO lista_paises(id,nome) VALUES (161, 'Norfork Island');
INSERT INTO lista_paises(id,nome) VALUES (162, 'Northern Mariana Islands');
INSERT INTO lista_paises(id,nome) VALUES (163, 'Norway');
INSERT INTO lista_paises(id,nome) VALUES (164, 'Oman');
INSERT INTO lista_paises(id,nome) VALUES (165, 'Pakistan');
INSERT INTO lista_paises(id,nome) VALUES (166, 'Palau');
INSERT INTO lista_paises(id,nome) VALUES (167, 'Panama');
INSERT INTO lista_paises(id,nome) VALUES (168, 'Papua New Guinea');
INSERT INTO lista_paises(id,nome) VALUES (169, 'Paraguay');
INSERT INTO lista_paises(id,nome) VALUES (170, 'Peru');
INSERT INTO lista_paises(id,nome) VALUES (171, 'Philippines');
INSERT INTO lista_paises(id,nome) VALUES (172, 'Pitcairn');
INSERT INTO lista_paises(id,nome) VALUES (173, 'Poland');
INSERT INTO lista_paises(id,nome) VALUES (174, 'Portugal');
INSERT INTO lista_paises(id,nome) VALUES (175, 'Puerto Rico');
INSERT INTO lista_paises(id,nome) VALUES (176, 'Qatar');
INSERT INTO lista_paises(id,nome) VALUES (177, 'Reunion');
INSERT INTO lista_paises(id,nome) VALUES (178, 'Romania');
INSERT INTO lista_paises(id,nome) VALUES (179, 'Russian Federation');
INSERT INTO lista_paises(id,nome) VALUES (180, 'Rwanda');
INSERT INTO lista_paises(id,nome) VALUES (181, 'Saint Kitts and Nevis');
INSERT INTO lista_paises(id,nome) VALUES (182, 'Saint Lucia');
INSERT INTO lista_paises(id,nome) VALUES (183, 'Saint Vincent and the Grenadines');
INSERT INTO lista_paises(id,nome) VALUES (184, 'Samoa');
INSERT INTO lista_paises(id,nome) VALUES (185, 'San Marino');
INSERT INTO lista_paises(id,nome) VALUES (186, 'Sao Tome and Principe');
INSERT INTO lista_paises(id,nome) VALUES (187, 'Saudi Arabia');
INSERT INTO lista_paises(id,nome) VALUES (188, 'Senegal');
INSERT INTO lista_paises(id,nome) VALUES (189, 'Serbia');
INSERT INTO lista_paises(id,nome) VALUES (190, 'Seychelles');
INSERT INTO lista_paises(id,nome) VALUES (191, 'Sierra Leone');
INSERT INTO lista_paises(id,nome) VALUES (192, 'Singapore');
INSERT INTO lista_paises(id,nome) VALUES (193, 'Slovakia');
INSERT INTO lista_paises(id,nome) VALUES (194, 'Slovenia');
INSERT INTO lista_paises(id,nome) VALUES (195, 'Solomon Islands');
INSERT INTO lista_paises(id,nome) VALUES (196, 'Somalia');
INSERT INTO lista_paises(id,nome) VALUES (197, 'South Africa');
INSERT INTO lista_paises(id,nome) VALUES (198, 'South Georgia South Sandwich Islands');
INSERT INTO lista_paises(id,nome) VALUES (199, 'Spain');
INSERT INTO lista_paises(id,nome) VALUES (200, 'Sri Lanka');
INSERT INTO lista_paises(id,nome) VALUES (201, 'St. Helena');
INSERT INTO lista_paises(id,nome) VALUES (202, 'St. Pierre and Miquelon');
INSERT INTO lista_paises(id,nome) VALUES (203, 'Sudan');
INSERT INTO lista_paises(id,nome) VALUES (204, 'Suriname');
INSERT INTO lista_paises(id,nome) VALUES (205, 'Svalbarn and Jan Mayen Islands');
INSERT INTO lista_paises(id,nome) VALUES (206, 'Swaziland');
INSERT INTO lista_paises(id,nome) VALUES (207, 'Sweden');
INSERT INTO lista_paises(id,nome) VALUES (208, 'Switzerland');
INSERT INTO lista_paises(id,nome) VALUES (209, 'Syrian Arab Republic');
INSERT INTO lista_paises(id,nome) VALUES (210, 'Taiwan');
INSERT INTO lista_paises(id,nome) VALUES (211, 'Tajikistan');
INSERT INTO lista_paises(id,nome) VALUES (212, 'Tanzania, United Republic of');
INSERT INTO lista_paises(id,nome) VALUES (213, 'Thailand');
INSERT INTO lista_paises(id,nome) VALUES (214, 'Togo');
INSERT INTO lista_paises(id,nome) VALUES (215, 'Tokelau');
INSERT INTO lista_paises(id,nome) VALUES (216, 'Tonga');
INSERT INTO lista_paises(id,nome) VALUES (217, 'Trinidad and Tobago');
INSERT INTO lista_paises(id,nome) VALUES (218, 'Tunisia');
INSERT INTO lista_paises(id,nome) VALUES (219, 'Turkey');
INSERT INTO lista_paises(id,nome) VALUES (220, 'Turkmenistan');
INSERT INTO lista_paises(id,nome) VALUES (221, 'Turks and Caicos Islands');
INSERT INTO lista_paises(id,nome) VALUES (222, 'Tuvalu');
INSERT INTO lista_paises(id,nome) VALUES (223, 'Uganda');
INSERT INTO lista_paises(id,nome) VALUES (224, 'Ukraine');
INSERT INTO lista_paises(id,nome) VALUES (225, 'United Arab Emirates');
INSERT INTO lista_paises(id,nome) VALUES (226, 'United Kingdom');
INSERT INTO lista_paises(id,nome) VALUES (227, 'United States minor outlying islands');
INSERT INTO lista_paises(id,nome) VALUES (228, 'Uruguay');
INSERT INTO lista_paises(id,nome) VALUES (229, 'Uzbekistan');
INSERT INTO lista_paises(id,nome) VALUES (230, 'Vanuatu');
INSERT INTO lista_paises(id,nome) VALUES (231, 'Vatican City State');
INSERT INTO lista_paises(id,nome) VALUES (232, 'Venezuela');
INSERT INTO lista_paises(id,nome) VALUES (233, 'Vietnam');
INSERT INTO lista_paises(id,nome) VALUES (234, 'Virgin Islands (British)');
INSERT INTO lista_paises(id,nome) VALUES (235, 'Virgin Islands (U.S.)');
INSERT INTO lista_paises(id,nome) VALUES (236, 'Wallis and Futuna Islands');
INSERT INTO lista_paises(id,nome) VALUES (237, 'Western Sahara');
INSERT INTO lista_paises(id,nome) VALUES (238, 'Yemen');
INSERT INTO lista_paises(id,nome) VALUES (239, 'Yugoslavia');
INSERT INTO lista_paises(id,nome) VALUES (240, 'Zaire');
INSERT INTO lista_paises(id,nome) VALUES (241, 'Zambia');
INSERT INTO lista_paises(id,nome) VALUES (242, 'Zimbabwe');