INSERT INTO paises(nome, qtd_participantes) VALUES ('Afghanistan',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Angola',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Amnesty International',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Argentina',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Argentina (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Australia',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Bolivia',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Bolívia (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Bosnia and Herzegovina',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Brazil' ,	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Brasil (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Cambodia',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Canada',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Central African Republic',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Chad',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('China, People\'s Republic of',	5);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Chile',	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Chile (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Colombia', 	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Colómbia (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Congo, Democratic Republic of the',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Ecuador',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Ecuador (CDS-UNASUR)**',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Egypt',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('European Union*',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Ethiopia',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Food and Agriculture Organization (FAO)*',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('France',	6);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Germany',	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Greenpeace',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Guatemala',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Guyana (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Greece',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Haiti',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Human Rights Watch*',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('India',	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Indonesia',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Iran',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Iraq',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Israel*',	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Japan',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Jordan',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Kenya',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Lithuania',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Lybia',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Mexico*',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('México (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Morocco',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Malaysia',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Netherlands',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('New Zealand',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Niger',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Nigeria',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Norway	1', 1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Palestine*',	4);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Panamá (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Paraguay (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Perú (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Philippines',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Russia',	5);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Rwanda',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Saudi Arabia',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Somalia',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('South Africa',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('South Korea',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Spain',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Sudan',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Suriname (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Sweden',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Switzerland',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Syria',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Turkey',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Uganda',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('USA',	6);
INSERT INTO paises(nome, qtd_participantes) VALUES ('United Kingdom',	6);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Uruguay (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Venezuela',	3);
INSERT INTO paises(nome, qtd_participantes) VALUES ('Venezuela (CDS-UNASUR)',	2);
INSERT INTO paises(nome, qtd_participantes) VALUES ('World Food Programme (WFP)',	1);
INSERT INTO paises(nome, qtd_participantes) VALUES ('World Wide Fund for Nature (WWF)',	1);